### ISSUE TITLE
Reorder classes to deeper

### ISSUE THREAD

**Issue by tigokr** [elegant-bro/stringify#20]
I think we should move different files to submodules, like this
Base64* to Encode
Json* to Encode
UUID to Generator
Join, SubOf, Trim etc to String
and other

Because in future we will take more files to src folder and at one moment project navigation will become painful

**Comment by stepanets** [comment]
Agree. What about this structure?

- Base64
  - Base64Encoded (rename to Encoded?)
  - Base64Decoded (rename to Decoded?)
- Date
  - FormattedDate (rename to Formatted?)
- File
  - Content
  - RealPath
- Hash
  - Algo
  - Hashed
- Json
  - JsonEncoded (rename to Encoded?)
- Random
  - UUIDv4
- Strings
  - EmptyStr (rename to Blank?)
  - Imploded
  - Formatted
  - Joined
  - Just
  - LeftTrimmed
  - NotEmpty (rename to NotBlank?)
  - Replaced
  - RightTrimmed
  - SubOf
  - ToString
  - Trimmed
- Cahed (in Stringify NS)
- FromCallable (in Stringify NS)

Maybe we should create `Valid` namespace for such classes as NotEmptyStr, because it makes validation only
- Valid
  - NotBlank
  - SslVerified
  - ...

But it also can be the responsibility of some `ElegantBro\Boolean` library

**Comment by tigokr** [comment]
totally agree with first part
maybe Predicates or Expression would be better?

**Comment by stepanets** [comment]
Defently not Predicates. Expression is not good too.  Maybe `Assertion`? But I'm no shure that it's `Stringify` responsibility. 
@DrBallMD what do you think about?

**Comment by tigokr** [comment]
> Defently not Predicates. Expression is not good too. Maybe `Assertion`? But I'm no shure that it's `Stringify` responsibility.
> @DrBallMD what do you think about?

i forget... it's about `Valid` namespace?

**Comment by stepanets** [comment]
yeap

**Comment by stepanets** [comment]
Let's leave NotBlank is Strings ns
